export default {
  // ko: 'Korean',
  en: 'English',
  'zh-CN': 'simple Chinese',
  'zh-TW': 'traditional Chinese',
  ja: 'Japanese',
  // hi: 'Hindi',
  es: 'Espanol',
  fr: 'French',
  de: 'Deutsch',
  // pt: 'Portuguese',
  vi: 'Vietnamese',
  id: 'Indonesian',
  // fa: 'Farsee',
  // ar: 'Arabian',
  // mm: 'Myanmarese',
  th: 'Thai',
  ru: 'Russian',
  it: 'Italian',
};
